/*
 RlToml: DBS Parser auto-generated by the Kaitai Struct compiler
 Copyright (C) 2026 luvlsco

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#![allow(unused_imports)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(irrefutable_let_patterns)]
#![allow(unused_comparisons)]
#![allow(dead_code)]
#![allow(clippy::all)]

extern crate kaitai;
use kaitai::*;
use std::cell::{Cell, Ref, RefCell};
use std::convert::{TryFrom, TryInto};
use std::rc::{Rc, Weak};

/**
 * \sa https://github.com/rinrin-/crass/blob/master/cui/RealLive/RealLive.cpp#L678 Source
 */

#[derive(Default, Debug, Clone)]
pub struct DbsParser {
    pub _root: SharedType<DbsParser>,
    pub _parent: SharedType<DbsParser>,
    pub _self: SharedType<Self>,
    string_end: RefCell<u32>,
    num_row_ids: RefCell<u32>,
    num_types: RefCell<u32>,
    row_id_offset: RefCell<u32>,
    type_list_offset: RefCell<u32>,
    value_list_offset: RefCell<u32>,
    string_table_offset: RefCell<u32>,
    _io: RefCell<BytesReader>,
    f_row_ids: Cell<bool>,
    row_ids: RefCell<Vec<u32>>,
    f_rows: Cell<bool>,
    rows: RefCell<Vec<OptRc<DbsParser_Row>>>,
    f_string_table_raw: Cell<bool>,
    string_table_raw: RefCell<Vec<u8>>,
    f_types: Cell<bool>,
    types: RefCell<Vec<OptRc<DbsParser_ColumnTypeEntry>>>,
    f_values: Cell<bool>,
    values: RefCell<Vec<u32>>,
}
impl KStruct for DbsParser {
    type Root = DbsParser;
    type Parent = DbsParser;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        *self_rc.string_end.borrow_mut() = _io.read_u4le()?.into();
        *self_rc.num_row_ids.borrow_mut() = _io.read_u4le()?.into();
        *self_rc.num_types.borrow_mut() = _io.read_u4le()?.into();
        *self_rc.row_id_offset.borrow_mut() = _io.read_u4le()?.into();
        *self_rc.type_list_offset.borrow_mut() = _io.read_u4le()?.into();
        *self_rc.value_list_offset.borrow_mut() = _io.read_u4le()?.into();
        *self_rc.string_table_offset.borrow_mut() = _io.read_u4le()?.into();
        Ok(())
    }
}
impl DbsParser {
    /**
     * Sequential row IDs (0, 1, 2, ..., num_row_ids-1)
     */
    pub fn row_ids(&self) -> KResult<Ref<'_, Vec<u32>>> {
        let _io = self._io.borrow();
        let _rrc = self._root.get_value().borrow().upgrade();
        let _prc = self._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        if self.f_row_ids.get() {
            return Ok(self.row_ids.borrow());
        }
        self.f_row_ids.set(true);
        let _pos = _io.pos();
        _io.seek(*self.row_id_offset() as usize)?;
        *self.row_ids.borrow_mut() = Vec::new();
        let l_row_ids = *self.num_row_ids();
        for _i in 0..l_row_ids {
            self.row_ids.borrow_mut().push(_io.read_u4le()?.into());
        }
        _io.seek(_pos)?;
        Ok(self.row_ids.borrow())
    }

    /**
     * Rows with each cell resolved according to its column's data_type
     */
    pub fn rows(&self) -> KResult<Ref<'_, Vec<OptRc<DbsParser_Row>>>> {
        let _io = self._io.borrow();
        let _rrc = self._root.get_value().borrow().upgrade();
        let _prc = self._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        if self.f_rows.get() {
            return Ok(self.rows.borrow());
        }
        self.f_rows.set(true);
        *self.rows.borrow_mut() = Vec::new();
        let l_rows = self.row_ids()?.len();
        for _i in 0..l_rows {
            let f = |t: &mut DbsParser_Row| {
                Ok(t.set_params((_i).try_into().map_err(|_| KError::CastError)?))
            };
            let t = Self::read_into_with_init::<_, DbsParser_Row>(
                &*_io,
                Some(self._root.clone()),
                Some(self._self.clone()),
                &f,
            )?
            .into();
            self.rows.borrow_mut().push(t);
        }
        Ok(self.rows.borrow())
    }

    /**
     * Raw string table bytes (SJIS, null-terminated)
     */
    pub fn string_table_raw(&self) -> KResult<Ref<'_, Vec<u8>>> {
        let _io = self._io.borrow();
        let _rrc = self._root.get_value().borrow().upgrade();
        let _prc = self._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        if self.f_string_table_raw.get() {
            return Ok(self.string_table_raw.borrow());
        }
        self.f_string_table_raw.set(true);
        let _pos = _io.pos();
        _io.seek(*self.string_table_offset() as usize)?;
        *self.string_table_raw.borrow_mut() = _io
            .read_bytes(
                ((*self.string_end() as u32) - (*self.string_table_offset() as u32)) as usize,
            )?
            .into();
        _io.seek(_pos)?;
        Ok(self.string_table_raw.borrow())
    }

    /**
     * Column type descriptors
     */
    pub fn types(&self) -> KResult<Ref<'_, Vec<OptRc<DbsParser_ColumnTypeEntry>>>> {
        let _io = self._io.borrow();
        let _rrc = self._root.get_value().borrow().upgrade();
        let _prc = self._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        if self.f_types.get() {
            return Ok(self.types.borrow());
        }
        self.f_types.set(true);
        let _pos = _io.pos();
        _io.seek(*self.type_list_offset() as usize)?;
        *self.types.borrow_mut() = Vec::new();
        let l_types = *self.num_types();
        for _i in 0..l_types {
            let t = Self::read_into::<_, DbsParser_ColumnTypeEntry>(
                &*_io,
                Some(self._root.clone()),
                Some(self._self.clone()),
            )?
            .into();
            self.types.borrow_mut().push(t);
        }
        _io.seek(_pos)?;
        Ok(self.types.borrow())
    }

    /**
     * Flat value array: string offsets (relative to string_table_offset) or raw integers
     */
    pub fn values(&self) -> KResult<Ref<'_, Vec<u32>>> {
        let _io = self._io.borrow();
        let _rrc = self._root.get_value().borrow().upgrade();
        let _prc = self._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        if self.f_values.get() {
            return Ok(self.values.borrow());
        }
        self.f_values.set(true);
        let _pos = _io.pos();
        _io.seek(*self.value_list_offset() as usize)?;
        *self.values.borrow_mut() = Vec::new();
        let l_values = (*self.num_row_ids() as u32) * (*self.num_types() as u32);
        for _i in 0..l_values {
            self.values.borrow_mut().push(_io.read_u4le()?.into());
        }
        _io.seek(_pos)?;
        Ok(self.values.borrow())
    }
}
impl DbsParser {
    pub fn string_end(&self) -> Ref<'_, u32> {
        self.string_end.borrow()
    }
}
impl DbsParser {
    pub fn num_row_ids(&self) -> Ref<'_, u32> {
        self.num_row_ids.borrow()
    }
}
impl DbsParser {
    pub fn num_types(&self) -> Ref<'_, u32> {
        self.num_types.borrow()
    }
}
impl DbsParser {
    pub fn row_id_offset(&self) -> Ref<'_, u32> {
        self.row_id_offset.borrow()
    }
}
impl DbsParser {
    pub fn type_list_offset(&self) -> Ref<'_, u32> {
        self.type_list_offset.borrow()
    }
}
impl DbsParser {
    pub fn value_list_offset(&self) -> Ref<'_, u32> {
        self.value_list_offset.borrow()
    }
}
impl DbsParser {
    pub fn string_table_offset(&self) -> Ref<'_, u32> {
        self.string_table_offset.borrow()
    }
}
impl DbsParser {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}
#[derive(Debug, PartialEq, Clone)]
pub enum DbsParser_ColumnType {
    String,
    Integer,
    Unknown(i64),
}

impl TryFrom<i64> for DbsParser_ColumnType {
    type Error = KError;
    fn try_from(flag: i64) -> KResult<DbsParser_ColumnType> {
        match flag {
            83 => Ok(DbsParser_ColumnType::String),
            86 => Ok(DbsParser_ColumnType::Integer),
            _ => Ok(DbsParser_ColumnType::Unknown(flag)),
        }
    }
}

impl From<&DbsParser_ColumnType> for i64 {
    fn from(v: &DbsParser_ColumnType) -> Self {
        match *v {
            DbsParser_ColumnType::String => 83,
            DbsParser_ColumnType::Integer => 86,
            DbsParser_ColumnType::Unknown(v) => v,
        }
    }
}

impl Default for DbsParser_ColumnType {
    fn default() -> Self {
        DbsParser_ColumnType::Unknown(0)
    }
}

#[derive(Default, Debug, Clone)]
pub struct DbsParser_Cell {
    pub _root: SharedType<DbsParser>,
    pub _parent: SharedType<DbsParser_Row>,
    pub _self: SharedType<Self>,
    row_idx: RefCell<u32>,
    col_idx: RefCell<u32>,
    _io: RefCell<BytesReader>,
    f_col_type: Cell<bool>,
    col_type: RefCell<DbsParser_ColumnType>,
    f_int_value: Cell<bool>,
    int_value: RefCell<u32>,
    f_raw_value: Cell<bool>,
    raw_value: RefCell<u32>,
    f_str_value: Cell<bool>,
    str_value: RefCell<String>,
}
impl KStruct for DbsParser_Cell {
    type Root = DbsParser;
    type Parent = DbsParser_Row;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        Ok(())
    }
}
impl DbsParser_Cell {
    pub fn row_idx(&self) -> Ref<'_, u32> {
        self.row_idx.borrow()
    }
}
impl DbsParser_Cell {
    pub fn col_idx(&self) -> Ref<'_, u32> {
        self.col_idx.borrow()
    }
}
impl DbsParser_Cell {
    pub fn set_params(&mut self, row_idx: u32, col_idx: u32) {
        *self.row_idx.borrow_mut() = row_idx;
        *self.col_idx.borrow_mut() = col_idx;
    }
}
impl DbsParser_Cell {
    pub fn col_type(&self) -> KResult<Ref<'_, DbsParser_ColumnType>> {
        let _io = self._io.borrow();
        let _rrc = self._root.get_value().borrow().upgrade();
        let _prc = self._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        if self.f_col_type.get() {
            return Ok(self.col_type.borrow());
        }
        self.f_col_type.set(true);
        *self.col_type.borrow_mut() =
            if *_r.types()?[*self.col_idx() as usize].data_type() == DbsParser_ColumnType::String {
                DbsParser_ColumnType::String.clone()
            } else {
                _r.types()?[*self.col_idx() as usize].data_type().clone()
            };
        Ok(self.col_type.borrow())
    }

    /**
     * Resolved integer when column data_type == integer
     */
    pub fn int_value(&self) -> KResult<Ref<'_, u32>> {
        let _io = self._io.borrow();
        let _rrc = self._root.get_value().borrow().upgrade();
        let _prc = self._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        if self.f_int_value.get() {
            return Ok(self.int_value.borrow());
        }
        self.f_int_value.set(true);
        if *self.col_type()? == DbsParser_ColumnType::Integer {
            *self.int_value.borrow_mut() = (*self.raw_value()?) as u32;
        }
        Ok(self.int_value.borrow())
    }

    /**
     * Underlying flat u4 value before interpretation
     */
    pub fn raw_value(&self) -> KResult<Ref<'_, u32>> {
        let _io = self._io.borrow();
        let _rrc = self._root.get_value().borrow().upgrade();
        let _prc = self._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        if self.f_raw_value.get() {
            return Ok(self.raw_value.borrow());
        }
        self.f_raw_value.set(true);
        *self.raw_value.borrow_mut() =
            (_r.values()?[((((*self.row_idx() as i32) * (*_r.num_types() as i32)) as i32)
                + (*self.col_idx() as i32)) as usize]) as u32;
        Ok(self.raw_value.borrow())
    }

    /**
     * Resolved string when column data_type == string
     */
    pub fn str_value(&self) -> KResult<Ref<'_, String>> {
        let _io = self._io.borrow();
        let _rrc = self._root.get_value().borrow().upgrade();
        let _prc = self._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        if self.f_str_value.get() {
            return Ok(self.str_value.borrow());
        }
        self.f_str_value.set(true);
        if *self.col_type()? == DbsParser_ColumnType::String {
            let io = Clone::clone(&*_r._io());
            let _pos = io.pos();
            io.seek(((*_r.string_table_offset() as u32) + (*self.raw_value()? as u32)) as usize)?;
            *self.str_value.borrow_mut() = bytes_to_str(
                &io.read_bytes_term(0, false, true, true)?.into(),
                "Shift_JIS",
            )?;
            io.seek(_pos)?;
        }
        Ok(self.str_value.borrow())
    }
}
impl DbsParser_Cell {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}

#[derive(Default, Debug, Clone)]
pub struct DbsParser_ColumnTypeEntry {
    pub _root: SharedType<DbsParser>,
    pub _parent: SharedType<DbsParser>,
    pub _self: SharedType<Self>,
    column_id: RefCell<u32>,
    data_type: RefCell<DbsParser_ColumnType>,
    _io: RefCell<BytesReader>,
}
impl KStruct for DbsParser_ColumnTypeEntry {
    type Root = DbsParser;
    type Parent = DbsParser;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        *self_rc.column_id.borrow_mut() = _io.read_u4le()?.into();
        *self_rc.data_type.borrow_mut() = (_io.read_u4le()? as i64).try_into()?;
        Ok(())
    }
}
impl DbsParser_ColumnTypeEntry {}

/**
 * Column identifier
 */
impl DbsParser_ColumnTypeEntry {
    pub fn column_id(&self) -> Ref<'_, u32> {
        self.column_id.borrow()
    }
}

/**
 * 0x53 = string (SJIS), 0x56 = integer
 */
impl DbsParser_ColumnTypeEntry {
    pub fn data_type(&self) -> Ref<'_, DbsParser_ColumnType> {
        self.data_type.borrow()
    }
}
impl DbsParser_ColumnTypeEntry {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}

#[derive(Default, Debug, Clone)]
pub struct DbsParser_Row {
    pub _root: SharedType<DbsParser>,
    pub _parent: SharedType<DbsParser>,
    pub _self: SharedType<Self>,
    row_idx: RefCell<u32>,
    _io: RefCell<BytesReader>,
    f_cells: Cell<bool>,
    cells: RefCell<Vec<OptRc<DbsParser_Cell>>>,
}
impl KStruct for DbsParser_Row {
    type Root = DbsParser;
    type Parent = DbsParser;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        Ok(())
    }
}
impl DbsParser_Row {
    pub fn row_idx(&self) -> Ref<'_, u32> {
        self.row_idx.borrow()
    }
}
impl DbsParser_Row {
    pub fn set_params(&mut self, row_idx: u32) {
        *self.row_idx.borrow_mut() = row_idx;
    }
}
impl DbsParser_Row {
    /**
     * One cell per column, resolved (string or integer) via cell type
     */
    pub fn cells(&self) -> KResult<Ref<'_, Vec<OptRc<DbsParser_Cell>>>> {
        let _io = self._io.borrow();
        let _rrc = self._root.get_value().borrow().upgrade();
        let _prc = self._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        if self.f_cells.get() {
            return Ok(self.cells.borrow());
        }
        self.f_cells.set(true);
        *self.cells.borrow_mut() = Vec::new();
        let l_cells = *_r.num_types();
        for _i in 0..l_cells {
            let f = |t: &mut DbsParser_Cell| {
                Ok(t.set_params(
                    (*self.row_idx())
                        .try_into()
                        .map_err(|_| KError::CastError)?,
                    (_i).try_into().map_err(|_| KError::CastError)?,
                ))
            };
            let t = Self::read_into_with_init::<_, DbsParser_Cell>(
                &*_io,
                Some(self._root.clone()),
                Some(self._self.clone()),
                &f,
            )?
            .into();
            self.cells.borrow_mut().push(t);
        }
        Ok(self.cells.borrow())
    }
}
impl DbsParser_Row {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}
