/* 
 RlToml: GAN parser generated by Kaitai Struct compiler
 Copyright (C) 2026 luvlsco

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#![allow(unused)]
#![allow(unused_imports)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(irrefutable_let_patterns)]
#![allow(unused_comparisons)]

extern crate kaitai;
use kaitai::*;
use std::convert::{TryFrom, TryInto};
use std::cell::{Ref, Cell, RefCell};
use std::rc::{Rc, Weak};

#[derive(Default, Debug, Clone)]
pub struct GanParser {
    pub _root: SharedType<GanParser>,
    pub _parent: SharedType<GanParser>,
    pub _self: SharedType<Self>,
    header: RefCell<OptRc<GanParser_Header>>,
    data_section: RefCell<OptRc<GanParser_DataSection>>,
    _io: RefCell<BytesReader>,
}
impl KStruct for GanParser {
    type Root = GanParser;
    type Parent = GanParser;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        let t = Self::read_into::<_, GanParser_Header>(&*_io, Some(self_rc._root.clone()), Some(self_rc._self.clone()))?.into();
        *self_rc.header.borrow_mut() = t;
        let t = Self::read_into::<_, GanParser_DataSection>(&*_io, Some(self_rc._root.clone()), Some(self_rc._self.clone()))?.into();
        *self_rc.data_section.borrow_mut() = t;
        Ok(())
    }
}
impl GanParser {
}
impl GanParser {
    pub fn header(&self) -> Ref<'_, OptRc<GanParser_Header>> {
        self.header.borrow()
    }
}
impl GanParser {
    pub fn data_section(&self) -> Ref<'_, OptRc<GanParser_DataSection>> {
        self.data_section.borrow()
    }
}
impl GanParser {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}

#[derive(Default, Debug, Clone)]
pub struct GanParser_DataSection {
    pub _root: SharedType<GanParser>,
    pub _parent: SharedType<GanParser>,
    pub _self: SharedType<Self>,
    data_section_marker: RefCell<u32>,
    num_sets: RefCell<u32>,
    sets: RefCell<Vec<OptRc<GanParser_DataSection_AnimationSet>>>,
    _io: RefCell<BytesReader>,
}
impl KStruct for GanParser_DataSection {
    type Root = GanParser;
    type Parent = GanParser;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        *self_rc.data_section_marker.borrow_mut() = _io.read_u4le()?.into();
        if !(((*self_rc.data_section_marker() as i32) == (20000 as i32))) {
            return Err(KError::ValidationFailed(ValidationFailedError { kind: ValidationKind::NotEqual, src_path: "/types/data_section/seq/0".to_string() }));
        }
        *self_rc.num_sets.borrow_mut() = _io.read_u4le()?.into();
        *self_rc.sets.borrow_mut() = Vec::new();
        let l_sets = *self_rc.num_sets();
        for _i in 0..l_sets {
            let t = Self::read_into::<_, GanParser_DataSection_AnimationSet>(&*_io, Some(self_rc._root.clone()), Some(self_rc._self.clone()))?.into();
            self_rc.sets.borrow_mut().push(t);
        }
        Ok(())
    }
}
impl GanParser_DataSection {
}
impl GanParser_DataSection {
    pub fn data_section_marker(&self) -> Ref<'_, u32> {
        self.data_section_marker.borrow()
    }
}
impl GanParser_DataSection {
    pub fn num_sets(&self) -> Ref<'_, u32> {
        self.num_sets.borrow()
    }
}
impl GanParser_DataSection {
    pub fn sets(&self) -> Ref<'_, Vec<OptRc<GanParser_DataSection_AnimationSet>>> {
        self.sets.borrow()
    }
}
impl GanParser_DataSection {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}

#[derive(Default, Debug, Clone)]
pub struct GanParser_DataSection_AnimationFrame {
    pub _root: SharedType<GanParser>,
    pub _parent: SharedType<GanParser_DataSection_AnimationSet>,
    pub _self: SharedType<Self>,
    entries: RefCell<Vec<OptRc<GanParser_DataSection_FrameEntry>>>,
    _io: RefCell<BytesReader>,
}
impl KStruct for GanParser_DataSection_AnimationFrame {
    type Root = GanParser;
    type Parent = GanParser_DataSection_AnimationSet;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        *self_rc.entries.borrow_mut() = Vec::new();
        {
            let mut _i = 0;
            while {
                let t = Self::read_into::<_, GanParser_DataSection_FrameEntry>(&*_io, Some(self_rc._root.clone()), Some(self_rc._self.clone()))?.into();
                self_rc.entries.borrow_mut().push(t);
                let _t_entries = self_rc.entries.borrow();
                let _tmpa = _t_entries.last().unwrap();
                _i += 1;
                let x = !(((*_tmpa.tag() as i32) == (999999 as i32)));
                x
            } {}
        }
        Ok(())
    }
}
impl GanParser_DataSection_AnimationFrame {
}
impl GanParser_DataSection_AnimationFrame {
    pub fn entries(&self) -> Ref<'_, Vec<OptRc<GanParser_DataSection_FrameEntry>>> {
        self.entries.borrow()
    }
}
impl GanParser_DataSection_AnimationFrame {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}

#[derive(Default, Debug, Clone)]
pub struct GanParser_DataSection_AnimationSet {
    pub _root: SharedType<GanParser>,
    pub _parent: SharedType<GanParser_DataSection>,
    pub _self: SharedType<Self>,
    set_marker: RefCell<u32>,
    num_frames: RefCell<u32>,
    frames: RefCell<Vec<OptRc<GanParser_DataSection_AnimationFrame>>>,
    _io: RefCell<BytesReader>,
}
impl KStruct for GanParser_DataSection_AnimationSet {
    type Root = GanParser;
    type Parent = GanParser_DataSection;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        *self_rc.set_marker.borrow_mut() = _io.read_u4le()?.into();
        if !(((*self_rc.set_marker() as i32) == (30000 as i32))) {
            return Err(KError::ValidationFailed(ValidationFailedError { kind: ValidationKind::NotEqual, src_path: "/types/data_section/types/animation_set/seq/0".to_string() }));
        }
        *self_rc.num_frames.borrow_mut() = _io.read_u4le()?.into();
        *self_rc.frames.borrow_mut() = Vec::new();
        let l_frames = *self_rc.num_frames();
        for _i in 0..l_frames {
            let t = Self::read_into::<_, GanParser_DataSection_AnimationFrame>(&*_io, Some(self_rc._root.clone()), Some(self_rc._self.clone()))?.into();
            self_rc.frames.borrow_mut().push(t);
        }
        Ok(())
    }
}
impl GanParser_DataSection_AnimationSet {
}
impl GanParser_DataSection_AnimationSet {
    pub fn set_marker(&self) -> Ref<'_, u32> {
        self.set_marker.borrow()
    }
}
impl GanParser_DataSection_AnimationSet {
    pub fn num_frames(&self) -> Ref<'_, u32> {
        self.num_frames.borrow()
    }
}
impl GanParser_DataSection_AnimationSet {
    pub fn frames(&self) -> Ref<'_, Vec<OptRc<GanParser_DataSection_AnimationFrame>>> {
        self.frames.borrow()
    }
}
impl GanParser_DataSection_AnimationSet {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}

#[derive(Default, Debug, Clone)]
pub struct GanParser_DataSection_FrameEntry {
    pub _root: SharedType<GanParser>,
    pub _parent: SharedType<GanParser_DataSection_AnimationFrame>,
    pub _self: SharedType<Self>,
    tag: RefCell<u32>,
    value: RefCell<i32>,
    _io: RefCell<BytesReader>,
}
impl KStruct for GanParser_DataSection_FrameEntry {
    type Root = GanParser;
    type Parent = GanParser_DataSection_AnimationFrame;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        *self_rc.tag.borrow_mut() = _io.read_u4le()?.into();
        if (*self_rc.tag() as i32) != (999999 as i32) {
            *self_rc.value.borrow_mut() = _io.read_s4le()?.into();
        }
        Ok(())
    }
}
impl GanParser_DataSection_FrameEntry {
}
impl GanParser_DataSection_FrameEntry {
    pub fn tag(&self) -> Ref<'_, u32> {
        self.tag.borrow()
    }
}
impl GanParser_DataSection_FrameEntry {
    pub fn value(&self) -> Ref<'_, i32> {
        self.value.borrow()
    }
}
impl GanParser_DataSection_FrameEntry {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}

#[derive(Default, Debug, Clone)]
pub struct GanParser_Header {
    pub _root: SharedType<GanParser>,
    pub _parent: SharedType<GanParser>,
    pub _self: SharedType<Self>,
    magic_1: RefCell<u32>,
    magic_2: RefCell<u32>,
    magic_3: RefCell<u32>,
    bitmap_name_len: RefCell<u32>,
    bitmap_name: RefCell<String>,
    _io: RefCell<BytesReader>,
}
impl KStruct for GanParser_Header {
    type Root = GanParser;
    type Parent = GanParser;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        *self_rc.magic_1.borrow_mut() = _io.read_u4le()?.into();
        if !(((*self_rc.magic_1() as i32) == (10000 as i32))) {
            return Err(KError::ValidationFailed(ValidationFailedError { kind: ValidationKind::NotEqual, src_path: "/types/header/seq/0".to_string() }));
        }
        *self_rc.magic_2.borrow_mut() = _io.read_u4le()?.into();
        if !(((*self_rc.magic_2() as i32) == (10000 as i32))) {
            return Err(KError::ValidationFailed(ValidationFailedError { kind: ValidationKind::NotEqual, src_path: "/types/header/seq/1".to_string() }));
        }
        *self_rc.magic_3.borrow_mut() = _io.read_u4le()?.into();
        if !(((*self_rc.magic_3() as i32) == (10100 as i32))) {
            return Err(KError::ValidationFailed(ValidationFailedError { kind: ValidationKind::NotEqual, src_path: "/types/header/seq/2".to_string() }));
        }
        *self_rc.bitmap_name_len.borrow_mut() = _io.read_u4le()?.into();
        *self_rc.bitmap_name.borrow_mut() = bytes_to_str(&_io.read_bytes_term(0, false, true, true)?.into(), "UTF-8")?;
        Ok(())
    }
}
impl GanParser_Header {
}
impl GanParser_Header {
    pub fn magic_1(&self) -> Ref<'_, u32> {
        self.magic_1.borrow()
    }
}
impl GanParser_Header {
    pub fn magic_2(&self) -> Ref<'_, u32> {
        self.magic_2.borrow()
    }
}
impl GanParser_Header {
    pub fn magic_3(&self) -> Ref<'_, u32> {
        self.magic_3.borrow()
    }
}
impl GanParser_Header {
    pub fn bitmap_name_len(&self) -> Ref<'_, u32> {
        self.bitmap_name_len.borrow()
    }
}
impl GanParser_Header {
    pub fn bitmap_name(&self) -> Ref<'_, String> {
        self.bitmap_name.borrow()
    }
}
impl GanParser_Header {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}
