/*
 RlToml: GAN Parser auto-generated by the Kaitai Struct compiler
 Copyright (C) 2026 luvlsco

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#![allow(unused_imports)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(irrefutable_let_patterns)]
#![allow(unused_comparisons)]
#![allow(dead_code)]

extern crate kaitai;
use kaitai::*;
use std::convert::{TryFrom, TryInto};
use std::cell::{Ref, Cell, RefCell};
use std::rc::{Rc, Weak};

/**
 * \sa https://github.com/eglaysher/rldev/tree/master/src/rlxml/gan.ml Source
 */

#[derive(Default, Debug, Clone)]
pub struct GanParser {
    pub _root: SharedType<GanParser>,
    pub _parent: SharedType<GanParser>,
    pub _self: SharedType<Self>,
    gan_header: RefCell<OptRc<GanParser_GanHeader>>,
    gan_data_section: RefCell<OptRc<GanParser_GanDataSection>>,
    _io: RefCell<BytesReader>,
}
impl KStruct for GanParser {
    type Root = GanParser;
    type Parent = GanParser;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        let t = Self::read_into::<_, GanParser_GanHeader>(&*_io, Some(self_rc._root.clone()), Some(self_rc._self.clone()))?.into();
        *self_rc.gan_header.borrow_mut() = t;
        let t = Self::read_into::<_, GanParser_GanDataSection>(&*_io, Some(self_rc._root.clone()), Some(self_rc._self.clone()))?.into();
        *self_rc.gan_data_section.borrow_mut() = t;
        Ok(())
    }
}
impl GanParser {
}
impl GanParser {
    pub fn gan_header(&self) -> Ref<'_, OptRc<GanParser_GanHeader>> {
        self.gan_header.borrow()
    }
}
impl GanParser {
    pub fn gan_data_section(&self) -> Ref<'_, OptRc<GanParser_GanDataSection>> {
        self.gan_data_section.borrow()
    }
}
impl GanParser {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}
#[derive(Debug, PartialEq, Clone)]
pub enum GanParser_Frame {
    Pattern,
    X,
    Y,
    Time,
    Alpha,
    Z,
    FrameEnd,
    Unknown(i64),
}

impl TryFrom<i64> for GanParser_Frame {
    type Error = KError;
    fn try_from(flag: i64) -> KResult<GanParser_Frame> {
        match flag {
            30100 => Ok(GanParser_Frame::Pattern),
            30101 => Ok(GanParser_Frame::X),
            30102 => Ok(GanParser_Frame::Y),
            30103 => Ok(GanParser_Frame::Time),
            30104 => Ok(GanParser_Frame::Alpha),
            30105 => Ok(GanParser_Frame::Z),
            999999 => Ok(GanParser_Frame::FrameEnd),
            _ => Ok(GanParser_Frame::Unknown(flag)),
        }
    }
}

impl From<&GanParser_Frame> for i64 {
    fn from(v: &GanParser_Frame) -> Self {
        match *v {
            GanParser_Frame::Pattern => 30100,
            GanParser_Frame::X => 30101,
            GanParser_Frame::Y => 30102,
            GanParser_Frame::Time => 30103,
            GanParser_Frame::Alpha => 30104,
            GanParser_Frame::Z => 30105,
            GanParser_Frame::FrameEnd => 999999,
            GanParser_Frame::Unknown(v) => v
        }
    }
}

impl Default for GanParser_Frame {
    fn default() -> Self { GanParser_Frame::Unknown(0) }
}


#[derive(Default, Debug, Clone)]
pub struct GanParser_GanDataSection {
    pub _root: SharedType<GanParser>,
    pub _parent: SharedType<GanParser>,
    pub _self: SharedType<Self>,
    data_section_marker: RefCell<u32>,
    num_sets: RefCell<u32>,
    sets: RefCell<Vec<OptRc<GanParser_GanDataSection_AnimationSet>>>,
    _io: RefCell<BytesReader>,
}
impl KStruct for GanParser_GanDataSection {
    type Root = GanParser;
    type Parent = GanParser;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        *self_rc.data_section_marker.borrow_mut() = _io.read_u4le()?.into();
        if !(((*self_rc.data_section_marker() as i32) == (20000 as i32))) {
            return Err(KError::ValidationFailed(ValidationFailedError { kind: ValidationKind::NotEqual, src_path: "/types/gan_data_section/seq/0".to_string() }));
        }
        *self_rc.num_sets.borrow_mut() = _io.read_u4le()?.into();
        *self_rc.sets.borrow_mut() = Vec::new();
        let l_sets = *self_rc.num_sets();
        for _i in 0..l_sets {
            let t = Self::read_into::<_, GanParser_GanDataSection_AnimationSet>(&*_io, Some(self_rc._root.clone()), Some(self_rc._self.clone()))?.into();
            self_rc.sets.borrow_mut().push(t);
        }
        Ok(())
    }
}
impl GanParser_GanDataSection {
}
impl GanParser_GanDataSection {
    pub fn data_section_marker(&self) -> Ref<'_, u32> {
        self.data_section_marker.borrow()
    }
}
impl GanParser_GanDataSection {
    pub fn num_sets(&self) -> Ref<'_, u32> {
        self.num_sets.borrow()
    }
}
impl GanParser_GanDataSection {
    pub fn sets(&self) -> Ref<'_, Vec<OptRc<GanParser_GanDataSection_AnimationSet>>> {
        self.sets.borrow()
    }
}
impl GanParser_GanDataSection {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}

#[derive(Default, Debug, Clone)]
pub struct GanParser_GanDataSection_AnimationFrame {
    pub _root: SharedType<GanParser>,
    pub _parent: SharedType<GanParser_GanDataSection_AnimationSet>,
    pub _self: SharedType<Self>,
    entries: RefCell<Vec<OptRc<GanParser_GanDataSection_FrameEntry>>>,
    _io: RefCell<BytesReader>,
}
impl KStruct for GanParser_GanDataSection_AnimationFrame {
    type Root = GanParser;
    type Parent = GanParser_GanDataSection_AnimationSet;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        *self_rc.entries.borrow_mut() = Vec::new();
        {
            let mut _i = 0;
            while {
                let t = Self::read_into::<_, GanParser_GanDataSection_FrameEntry>(&*_io, Some(self_rc._root.clone()), Some(self_rc._self.clone()))?.into();
                self_rc.entries.borrow_mut().push(t);
                let _t_entries = self_rc.entries.borrow();
                let _tmpa = _t_entries.last().unwrap();
                _i += 1;
                let x = !(*_tmpa.tag() == GanParser_Frame::FrameEnd);
                x
            } {}
        }
        Ok(())
    }
}
impl GanParser_GanDataSection_AnimationFrame {
}
impl GanParser_GanDataSection_AnimationFrame {
    pub fn entries(&self) -> Ref<'_, Vec<OptRc<GanParser_GanDataSection_FrameEntry>>> {
        self.entries.borrow()
    }
}
impl GanParser_GanDataSection_AnimationFrame {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}

#[derive(Default, Debug, Clone)]
pub struct GanParser_GanDataSection_AnimationSet {
    pub _root: SharedType<GanParser>,
    pub _parent: SharedType<GanParser_GanDataSection>,
    pub _self: SharedType<Self>,
    set_marker: RefCell<u32>,
    num_frames: RefCell<u32>,
    frames: RefCell<Vec<OptRc<GanParser_GanDataSection_AnimationFrame>>>,
    _io: RefCell<BytesReader>,
}
impl KStruct for GanParser_GanDataSection_AnimationSet {
    type Root = GanParser;
    type Parent = GanParser_GanDataSection;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        *self_rc.set_marker.borrow_mut() = _io.read_u4le()?.into();
        if !(((*self_rc.set_marker() as i32) == (30000 as i32))) {
            return Err(KError::ValidationFailed(ValidationFailedError { kind: ValidationKind::NotEqual, src_path: "/types/gan_data_section/types/animation_set/seq/0".to_string() }));
        }
        *self_rc.num_frames.borrow_mut() = _io.read_u4le()?.into();
        if !(((*self_rc.num_frames() as u32) >= (1 as u32))) {
            return Err(KError::ValidationFailed(ValidationFailedError { kind: ValidationKind::LessThan, src_path: "/types/gan_data_section/types/animation_set/seq/1".to_string() }));
        }
        *self_rc.frames.borrow_mut() = Vec::new();
        let l_frames = *self_rc.num_frames();
        for _i in 0..l_frames {
            let t = Self::read_into::<_, GanParser_GanDataSection_AnimationFrame>(&*_io, Some(self_rc._root.clone()), Some(self_rc._self.clone()))?.into();
            self_rc.frames.borrow_mut().push(t);
        }
        Ok(())
    }
}
impl GanParser_GanDataSection_AnimationSet {
}
impl GanParser_GanDataSection_AnimationSet {
    pub fn set_marker(&self) -> Ref<'_, u32> {
        self.set_marker.borrow()
    }
}
impl GanParser_GanDataSection_AnimationSet {
    pub fn num_frames(&self) -> Ref<'_, u32> {
        self.num_frames.borrow()
    }
}
impl GanParser_GanDataSection_AnimationSet {
    pub fn frames(&self) -> Ref<'_, Vec<OptRc<GanParser_GanDataSection_AnimationFrame>>> {
        self.frames.borrow()
    }
}
impl GanParser_GanDataSection_AnimationSet {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}

#[derive(Default, Debug, Clone)]
pub struct GanParser_GanDataSection_FrameEntry {
    pub _root: SharedType<GanParser>,
    pub _parent: SharedType<GanParser_GanDataSection_AnimationFrame>,
    pub _self: SharedType<Self>,
    tag: RefCell<GanParser_Frame>,
    value: RefCell<i32>,
    _io: RefCell<BytesReader>,
}
impl KStruct for GanParser_GanDataSection_FrameEntry {
    type Root = GanParser;
    type Parent = GanParser_GanDataSection_AnimationFrame;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        *self_rc.tag.borrow_mut() = (_io.read_u4le()? as i64).try_into()?;
        if !( ((*self_rc.tag() == GanParser_Frame::Pattern) || (*self_rc.tag() == GanParser_Frame::X) || (*self_rc.tag() == GanParser_Frame::Y) || (*self_rc.tag() == GanParser_Frame::Time) || (*self_rc.tag() == GanParser_Frame::Alpha) || (*self_rc.tag() == GanParser_Frame::Z) || (*self_rc.tag() == GanParser_Frame::FrameEnd)) ) {
            return Err(KError::ValidationFailed(ValidationFailedError { kind: ValidationKind::NotAnyOf, src_path: "/types/gan_data_section/types/frame_entry/seq/0".to_string() }));
        }
        if *self_rc.tag() != GanParser_Frame::FrameEnd {
            *self_rc.value.borrow_mut() = _io.read_s4le()?.into();
        }
        Ok(())
    }
}
impl GanParser_GanDataSection_FrameEntry {
}
impl GanParser_GanDataSection_FrameEntry {
    pub fn tag(&self) -> Ref<'_, GanParser_Frame> {
        self.tag.borrow()
    }
}
impl GanParser_GanDataSection_FrameEntry {
    pub fn value(&self) -> Ref<'_, i32> {
        self.value.borrow()
    }
}
impl GanParser_GanDataSection_FrameEntry {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}

#[derive(Default, Debug, Clone)]
pub struct GanParser_GanHeader {
    pub _root: SharedType<GanParser>,
    pub _parent: SharedType<GanParser>,
    pub _self: SharedType<Self>,
    magic_1: RefCell<u32>,
    magic_2: RefCell<u32>,
    magic_3: RefCell<u32>,
    bitmap_name_len: RefCell<u32>,
    bitmap_name: RefCell<String>,
    _io: RefCell<BytesReader>,
}
impl KStruct for GanParser_GanHeader {
    type Root = GanParser;
    type Parent = GanParser;

    fn read<S: KStream>(
        self_rc: &OptRc<Self>,
        _io: &S,
        _root: SharedType<Self::Root>,
        _parent: SharedType<Self::Parent>,
    ) -> KResult<()> {
        *self_rc._io.borrow_mut() = _io.clone();
        self_rc._root.set(_root.get());
        self_rc._parent.set(_parent.get());
        self_rc._self.set(Ok(self_rc.clone()));
        let _rrc = self_rc._root.get_value().borrow().upgrade();
        let _prc = self_rc._parent.get_value().borrow().upgrade();
        let _r = _rrc.as_ref().unwrap();
        *self_rc.magic_1.borrow_mut() = _io.read_u4le()?.into();
        if !(((*self_rc.magic_1() as i32) == (10000 as i32))) {
            return Err(KError::ValidationFailed(ValidationFailedError { kind: ValidationKind::NotEqual, src_path: "/types/gan_header/seq/0".to_string() }));
        }
        *self_rc.magic_2.borrow_mut() = _io.read_u4le()?.into();
        if !(((*self_rc.magic_2() as i32) == (10000 as i32))) {
            return Err(KError::ValidationFailed(ValidationFailedError { kind: ValidationKind::NotEqual, src_path: "/types/gan_header/seq/1".to_string() }));
        }
        *self_rc.magic_3.borrow_mut() = _io.read_u4le()?.into();
        if !(((*self_rc.magic_3() as i32) == (10100 as i32))) {
            return Err(KError::ValidationFailed(ValidationFailedError { kind: ValidationKind::NotEqual, src_path: "/types/gan_header/seq/2".to_string() }));
        }
        *self_rc.bitmap_name_len.borrow_mut() = _io.read_u4le()?.into();
        *self_rc.bitmap_name.borrow_mut() = bytes_to_str(&_io.read_bytes_term(0, false, true, true)?.into(), "Shift_JIS")?;
        Ok(())
    }
}
impl GanParser_GanHeader {
}
impl GanParser_GanHeader {
    pub fn magic_1(&self) -> Ref<'_, u32> {
        self.magic_1.borrow()
    }
}
impl GanParser_GanHeader {
    pub fn magic_2(&self) -> Ref<'_, u32> {
        self.magic_2.borrow()
    }
}
impl GanParser_GanHeader {
    pub fn magic_3(&self) -> Ref<'_, u32> {
        self.magic_3.borrow()
    }
}
impl GanParser_GanHeader {
    pub fn bitmap_name_len(&self) -> Ref<'_, u32> {
        self.bitmap_name_len.borrow()
    }
}
impl GanParser_GanHeader {
    pub fn bitmap_name(&self) -> Ref<'_, String> {
        self.bitmap_name.borrow()
    }
}
impl GanParser_GanHeader {
    pub fn _io(&self) -> Ref<'_, BytesReader> {
        self._io.borrow()
    }
}
